name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd src/RecordVisitors
        dotnet restore
    - name: Build
      run: |
        cd src/RecordVisitors
        dotnet build --no-restore
    - name: Test
      run: |
        cd src/RecordVisitors
        dotnet test --no-build --verbosity normal
    - name: Pack
      run: |
        cd src/RecordVisitors/RecordVisitors
        dotnet pack --include-source --include-symbols
