name: BuildAndTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1	
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: |
        cd src/RecordVisitors
        dotnet restore
    - name: Build
      run: |
        cd src/RecordVisitors
        dotnet build --no-restore
    - name: Test
      run: |
        cd src/RecordVisitors
        dotnet test --no-build --verbosity normal --logger:"console;verbosity=normal"
    - name: code coverage
      run: |
        cd src/RecordVisitors
        dotnet tool restore
        dotnet coverlet AutomatedTestRecord\bin\Debug\net5.0\AutomatedTestRecord.dll --target "dotnet" --targetargs "test RecordVisitors.sln --no-build"  --format opencover --exclude "[SampleWeb*]*"  --exclude "[xunit*]*" --verbosity detailed
        #dotnet coverlet AutomatedTestRecord\bin\Debug\net5.0\AutomatedTestRecord.dll --target "dotnet" --targetargs "test RecordVisitors.sln"  --format opencover  --verbosity detailed
        dotnet reportgenerator "-reports:coverage.opencover.xml" "-targetdir:coveragereport" "-reporttypes:HTMLInline;HTMLSummary;Badges"


    - name: verify code coverage
      run: |
        ls src/RecordVisitors/coverage.opencover.xml 

    - uses: codecov/codecov-action@v1
      with:
        files: src/RecordVisitors/coverage.opencover.xml 
        fail_ci_if_error: true # optional (default = false)
        #verbose: true # optional (default = false)
    - name: Pack
      run: |
        cd src/RecordVisitors/
        dotnet pwsh readme.ps1
        dotnet pwsh setVersion.ps1
        cd RecordVisitors
        dotnet pack -o nugetPackages 

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: RecordVisitorsNuget_${{github.run_number}}
        path: src/RecordVisitors/RecordVisitors/nugetPackages
        retention-days: 1
  
    - name: Generating documentation
      run: |
        cd src/RecordVisitors/        
        dotnet mddocs apireference --assembly .\RecordVisitors\bin\Debug\net5.0\RecordVisitors.dll -o docs

    - name: 'Upload Docs'
      uses: actions/upload-artifact@v2
      with:
        name: Docs_${{github.run_number}}
        path: src/RecordVisitors/docs
        retention-days: 1

    - name: 'Upload lightBDD'
      uses: actions/upload-artifact@v2
      with:
        name: LightBDD_${{github.run_number}}
        path: src/RecordVisitors/AutomatedTestRecord/bin/Debug/net5.0/Reports
        retention-days: 1

    - name: Build and analyze
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
        cd src/RecordVisitors
        dotnet dotnet-sonarscanner begin /k:"ignatandrei_RecordVisitors" /o:"ignatandrei-github" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"        
        dotnet build
        dotnet dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
